"""
app.py

Purpose:
    FastAPI backend exposing a /predict endpoint for the Garbage Detection
    System. Accepts an uploaded image and returns detected garbage classes,
    confidence scores, and bounding boxes as JSON.

    Uses the same shared GarbageDetector (detector.py) as the image, video,
    and webcam scripts - so API results are guaranteed identical to what
    you saw in local testing.

Run locally:
    cd backend
    uvicorn app:app --reload --port 8000

Then test at:
    http://localhost:8000/docs   (interactive Swagger UI - auto-generated by FastAPI)
"""

from fastapi import FastAPI, File, UploadFile, HTTPException
import numpy as np
import cv2

from detector import GarbageDetector

app = FastAPI(
    title="Garbage Detection API",
    description="Detects garbage objects in images using a fine-tuned YOLOv8s model.",
    version="1.0.0",
)

# Load the model ONCE when the server starts - not per-request.
# This is why detector is created here, at module level, rather than
# inside the predict() function below.
detector = GarbageDetector(model_path="../models/best.pt", conf_threshold=0.4)


@app.get("/")
def health_check():
    """
    Simple health-check endpoint. Lets you (or Hugging Face Spaces, or
    the Streamlit frontend) confirm the API is up and running before
    calling /predict.
    """
    return {"status": "ok", "message": "Garbage Detection API is running."}


@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    """
    Accepts an uploaded image file and returns detected garbage objects.

    Input:
        file: an uploaded image (jpg/png/etc.), sent as multipart/form-data.

    Output (JSON):
        {
            "detections": [
                {
                    "class": "plastic",
                    "confidence": 0.87,
                    "bounding_box": {"x1": 34.0, "y1": 12.0, "x2": 210.0, "y2": 190.0}
                },
                ...
            ]
        }
    """
    # Basic validation - reject non-image uploads early with a clear error,
    # instead of letting OpenCV fail with a confusing internal error later.
    if not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Uploaded file must be an image.")

    # Read the raw uploaded bytes.
    contents = await file.read()

    # Convert raw bytes -> numpy array -> decoded image (BGR, OpenCV format).
    # This is the standard way to turn an in-memory uploaded file into
    # something OpenCV/YOLO can process, without saving it to disk first.
    np_array = np.frombuffer(contents, np.uint8)
    image = cv2.imdecode(np_array, cv2.IMREAD_COLOR)

    if image is None:
        raise HTTPException(status_code=400, detail="Could not decode the uploaded image.")

    # Run detection - the exact same function used by image_detector.py,
    # video_detector.py, and webcam_detector.py.
    _, detections = detector.detect(image)

    return {"detections": detections}
